### ISSUE TITLE
☔ Konnect managed entities

### ISSUE THREAD

**Issue by lahabana** [Kong/kong-operator#370]
## Problem Statement

Users would like to manage Konnect entities directly from Kubernetes resources.
This issue is the main tracker to cover having CRD routes for things like: Service, Consumers, Routes.

The goal is to have a semi-automatic way to add support for entities in [platform-api](https://github.com/Kong/platform-api). This is necessary to minimise future work when new Konnect entities are added.

## Proposed Solution

Pending Product brief and Engineering brief.

Some open questions:

- How does relationship work?
- What's in status/condition?
- Can you mix entities managed by CRDs and non.

## Additional Information

Some useful reads:

- [Discovery doc](https://docs.google.com/document/d/1kziSy7EJbK58CxNuvcb8K3ndvLISLa3xj1b1unKMnOA/edit#heading=h.b541v0hlhgqz)

Implementation uses https://github.com/Kong/sdk-konnect-go/ to interact with Konnect which is generated from https://github.com/Kong/platform-api.

## Acceptance Criteria

```[tasklist]
### Design
- [ ] #382
```

```[tasklist]
### Implementation - August demo scope
- [ ] https://github.com/Kong/gateway-operator/issues/442
- [ ] #437
- [ ] #431
- [ ] #432
- [ ] #433
- [ ] #435
- [ ] #436
- [ ] #514
- [ ] #438
- [ ] #447
- [ ] https://github.com/Kong/gateway-operator/issues/481
- [ ] https://github.com/Kong/gateway-operator/issues/480
- [ ] https://github.com/Kong/gateway-operator/issues/530
- [ ] https://github.com/Kong/gateway-operator/issues/519
```

```[tasklist]
### Implementation - GA scope (October-ish)
- [ ] https://github.com/Kong/gateway-operator/issues/449
- [ ] https://github.com/Kong/gateway-operator/issues/575
- [ ] https://github.com/Kong/gateway-operator/issues/576
- [ ] https://github.com/Kong/gateway-operator/issues/577
- [ ] https://github.com/Kong/gateway-operator/issues/581
- [ ] https://github.com/Kong/gateway-operator/issues/582
- [ ] https://github.com/Kong/gateway-operator/issues/584
- [ ] https://github.com/Kong/gateway-operator/issues/585
- [ ] https://github.com/Kong/gateway-operator/issues/598
- [ ] https://github.com/Kong/gateway-operator/issues/608
- [ ] https://github.com/Kong/gateway-operator/issues/617
- [ ] https://github.com/Kong/gateway-operator/issues/619
- [ ] https://github.com/Kong/gateway-operator/issues/620
- [ ] https://github.com/Kong/gateway-operator/issues/621
- [ ] https://github.com/Kong/gateway-operator/issues/622
- [ ] https://github.com/Kong/gateway-operator/issues/451
- [ ] https://github.com/Kong/gateway-operator/issues/525
- [ ] https://github.com/Kong/gateway-operator/issues/526
- [ ] https://github.com/Kong/gateway-operator/issues/527
- [ ] https://github.com/Kong/gateway-operator/issues/528
- [ ] https://github.com/Kong/gateway-operator/issues/529
- [ ] https://github.com/Kong/gateway-operator/issues/552
- [ ] https://github.com/Kong/gateway-operator/issues/583
- [ ] https://github.com/Kong/kubernetes-configuration/issues/99
- [ ] https://github.com/Kong/gateway-operator/issues/665
- [ ] https://github.com/Kong/gateway-operator/issues/596
- [ ] https://github.com/Kong/gateway-operator/issues/706
- [ ] https://github.com/Kong/gateway-operator/pull/718
```

```[tasklist]
### Documentation
- [ ] https://github.com/Kong/gateway-operator/issues/439
- [ ] https://github.com/Kong/gateway-operator/issues/568
```

```[tasklist]
### Related issues
- [x] Making `/organizations/me` public for use in public konnect-sdk-go: https://konghq.atlassian.net/browse/TPS-2267, https://github.com/Kong/platform-api/pull/704
- [ ] https://github.com/Kong/khcp/pull/8011
```

**Comment by pmalek** [comment]
#827 covers the Post GA issues for this epic.
