### ISSUE TITLE
☔ Custom plugin distribution

### ISSUE THREAD

**Issue by lahabana** [Kong/kong-operator#371]
## Problem Statement

Custom plugins are a large part of customer deployments, but getting these plugins deployed and configured with a Kong Gateway instance has been painful. Since KGO aims to offer the E2E operational model for Kong Gateway on Kubernetes it should provide a way to ship and use custom plugins with Kong Gateways deployed and managed by KGO.

## Proposed Solution

Documents:

The most up-to-date and comprehensive [Engineering brief](https://docs.google.com/document/d/1-gYEaf_31BR_QXmZXNhy0bOrXYJ4X_cXobQ_vbLDIhE/edit#heading=h.9ikojn8u15x) that was created based on the 
- [Kong Gateway Plugin Distribution](https://docs.google.com/document/d/1fGPjikjqSRW-jNtKgzzMVi2rUSXY1XvwZOaPMPA1dtM)
- [Kong Custom Plugin Management for Kubernetes](https://docs.google.com/document/d/1T9GNeBf9sSzMSKE7pAJXVc8MpDPVWXNFvDKVWcmFwSw)
- [Product Brief: Custom Plugin Streaming](https://konghq.atlassian.net/wiki/spaces/PM/pages/3391291407/Product+Brief+Custom+Plugin+Streaming)

## Acceptance Criteria
- [x] A user can write a custom plugin that's up to 1MB put it in their OCI registry and run it by installing a CRD
- [x] Documentation is available
- [x] User call scheduled to demonstrate this feature

### Core scope/functionaliies
- [x] #113
- [x] #378 
- [x] #379
- [x] #610
- [x] #380
- [x] #381

### Additional, but still important
- [x] #465

### Nice to have
- [x] #521

## Issues for future milestones

- [x] #372
