### ISSUE TITLE
Konnect entities: add official documentation how KGO can manage Konnect entities

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#439]
### Problem statement

#370 introduces Konnect entity management in KGO. This task tracks the documentation effort for this.

```[tasklist]
### Tasks
- [x] KongRoute and KongService guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] KongConsumer and Credentials guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] KongKey and KeySet guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] KongPluginBinding guide https://github.com/Kong/docs.konghq.com/pull/8049
- [x] KongUpstream and Target guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] Tagging and labeling entities guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] KongCertificate, CACertificate and SNI guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] KongVault guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] DataPlaneClientCertificate guide https://github.com/Kong/docs.konghq.com/pull/8084
- [x] Architecture reference https://github.com/Kong/docs.konghq.com/pull/8084
```

### Acceptance criteria

- [x] A guide at https://docs.konghq.com/gateway-operator/latest/ exists which explains users how they can use KGO to manage Konnect entities.
- [ ] Someone with less familiarity with the feature does e2e manual tests based on what is in the docs

**Comment by czeslavo** [comment]
I'm assigning this to myself - I'll try to bootstrap docs for Konnect entities.

**Comment by pmalek** [comment]
I'm working on the architecture reference page.

EDIT:

Added under https://github.com/Kong/docs.konghq.com/pull/8084#:~:text=https%3A//deploy%2Dpreview%2D8084%2D%2Dkongdocs.netlify.app/gateway%2Doperator/unreleased/guides/konnect%2Dentities/architecture/ 

https://deploy-preview-8084--kongdocs.netlify.app/gateway-operator/unreleased/guides/konnect-entities/architecture/

**Comment by pmalek** [comment]
I believe this is done now. The last AC to be fulfilled now is 

> Someone with less familiarity with the feature does e2e manual tests based on what is in the docs

which I believe will be solved once @rspurgeon or @mheap finish their testing.

**Comment by pmalek** [comment]
Closing as testing has been concluded.
